# Generated by Django 5.1.1 on 2024-09-23 19:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parish',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='parish',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='parish',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
