# Generated by Django 5.1.1 on 2024-09-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_remove_inspection_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parish',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='parish_pictures/'),
        ),
    ]
