# Generated by Django 5.1.1 on 2024-09-23 20:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_parish_created_at_alter_parish_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='date_created',
        ),
        migrations.AddField(
            model_name='inspection',
            name='cableway_caps_present',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], default='dont_know', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='cableway_supports_secure',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], default='dont_know', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='cableway_surfacing_condition',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], default='dont_know', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='cableway_traveller_smooth',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], default='dont_know', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='cableway_unit_stable',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], default='dont_know', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='climber_components_secure',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], default='dont_know', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='climber_holds_present',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], default='dont_know', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='climber_logs_secure',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], default='dont_know', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='climber_surfacing_condition',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], default='dont_know', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='climber_unit_stable',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], default='dont_know', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='inspection',
            name='general_surfaces_debris',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], default='dont_know', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='general_surfaces_grids',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], default='dont_know', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='litter_bins_empty',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], default='dont_know', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='litter_bins_secure',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], default='dont_know', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='logs_free_of_decay',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], default='dont_know', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='logs_secure',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], default='dont_know', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='logs_surfacing_condition',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], default='dont_know', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='seating_stable',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], default='dont_know', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='signage',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], default='dont_know', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='slide_clean',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], default='dont_know', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='slide_secure',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], default='dont_know', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='slide_surfacing_condition',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], default='dont_know', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='swing_caps_fitted',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], default='dont_know', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='swing_chains_wear',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], default='dont_know', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='swing_seats_secure',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], default='dont_know', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='swing_supports_secure',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], default='dont_know', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='swing_surfacing_condition',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], default='dont_know', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='swing_unit_stable',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], default='dont_know', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='tunnel_clean',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], default='dont_know', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='tunnel_damage_free',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], default='dont_know', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='tunnel_palisade_stable',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], default='dont_know', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='tunnel_surfacing_condition',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], default='dont_know', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='parish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='inspections.parish'),
        ),
    ]
