# Generated by Django 5.1.1 on 2024-09-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_remove_inspection_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='cableway_suspension_chain',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], default='dont_know', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='cableway_take_off',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], default='dont_know', max_length=10),
        ),
    ]
