# Generated by Django 5.1.1 on 2024-09-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_parish_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parish',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='parish',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/'),
        ),
    ]
